create table if not exists public.ai_feedback (
  id bigint generated by default as identity primary key,
  assistant_message_id bigint not null references public.ai_messages(id) on delete cascade,
  telegram_user_id bigint not null,
  rating smallint not null check (rating in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assistant_message_id, telegram_user_id)
);

alter table public.ai_feedback enable row level security;
revoke all on table public.ai_feedback from anon, authenticated;
grant select, insert, update, delete on table public.ai_feedback to service_role;

drop policy if exists "service role manages ai feedback" on public.ai_feedback;
create policy "service role manages ai feedback"
on public.ai_feedback
for all
to service_role
using (true)
with check (true);

create index if not exists ai_feedback_user_created_idx
on public.ai_feedback (telegram_user_id, created_at desc);
