create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null,
  role text not null check (role in ('user','assistant')),
  content text not null check (char_length(content) between 1 and 4000),
  created_at timestamptz not null default now()
);

alter table public.ai_messages enable row level security;
revoke all on table public.ai_messages from anon, authenticated;
grant select, insert, delete on table public.ai_messages to service_role;

drop policy if exists "service role manages ai messages" on public.ai_messages;
create policy "service role manages ai messages"
on public.ai_messages
for all
to service_role
using (true)
with check (true);

create index if not exists ai_messages_user_created_idx
  on public.ai_messages (telegram_user_id, created_at desc);
